const Menu = [{
  id: 1,
  image: 'images/maggi.jpg',
  name: 'maggi',
  category: 'breakfast',
  price: 25,
  description: 'lorem1dfgs  dgfsd dgfsd lorem30',
},
{
  id: 2,
  image: 'images/allupakoida.jpg',
  name: 'Allupakoida',
  category: 'evening',
  price: 70,
  description: 'lorem1dfgs  dgfsd dgfsd',
},
{
  id: 3,
  image: 'images/corn.jpg',
  name: 'Corn',
  category: 'breakfast',
  price: 50,
  description: 'lorem1dfgs  dgfsd dgfsd',
},
{
  id: 4,
  image: 'images/chola.jpg',
  name: 'Chola',
  category: 'lunch',
  price: 80,
  description: 'lorem1dfgs  dgfsd dgfsd',
},
{
  id: 5,
  image: 'images/pizza.jpg',
  name: 'Pizza',
  category: 'evening',
  price: 120,
  description: 'lorem1dfgs  dgfsd dgfsd',
},
{
  id: 6,
  image: 'images/nonvegthali.jpg',
  name: 'Non-Veg Thali',
  category: 'dinner',
  price: 100,
  description: 'lorem1dfgs  dgfsd dgfsd',
},
{
  id: 7,
  image: 'images/sweet.jpg',
  name: 'Sweets',
  category: 'dinner',
  price: 50,
  description: 'lorem1dfgs  dgfsd dgfsd',
},
{
  id: 8,
  image: 'images/rajmarice.jpg',
  name: 'Rajma Rice',
  category: 'lunch',
  price: 60,
  description: 'lorem1dfgs  dgfsd dgfsd',
},
{
  id: 9,
  image: 'images/samosa.jpg',
  name: 'Samosa',
  category: 'evening',
  price: 10,
  description: 'lorem1dfgs  dgfsd dgfsd',
},


];
export default Menu;